### ISSUE TITLE
Advanced CLI commands

### ISSUE THREAD

**Issue by nikosdion** [akeeba/panopticon#153]
Complete the collection of CLI commands to manage every aspect of Panopticon through the command line.

## Site configuration management
* [ ] `sites:config:list`
* [ ] `sites:config:get`
* [ ] `sites:config:set`

## Miscellaneous site management
* [ ] `sites:overrides:list` List template overrides to check
* [ ] `sites:overrides:info` Information on a specific override

## Site: Akeeba Backup integration
* [ ] `sites:backup:schedule:list`
* [ ] `sites:backup:schedule:add`
* [ ] `sites:backup:schedule:remove`
* [ ] `sites:backup:schedule:enable`
* [ ] `sites:backup:schedule:disable`

## Site: Admin Tools integration
* [ ] `sites:scanner:schedule:list`
* [ ] `sites:scanner:schedule:add`
* [ ] `sites:scanner:schedule:remove`
* [ ] `sites:scanner:schedule:enable`
* [ ] `sites:scanner:schedule:disable`
* [ ] `sites:security:unblock`
* [ ] `sites:security:disable`
* [ ] `sites:security:enable`
* [ ] `sites:security:htaccess:disable`
* [ ] `sites:security:htaccess:enable`

## User management
* [ ] `user:list`
* [ ] `user:delete`
* [ ] `user:config:list`
* [ ] `user:config:get`
* [ ] `user:config:set`

## Groups management
* [ ] `group:list`
* [ ] `group:add`
* [ ] `group:delete`
* [ ] `group:config:get`
* [ ] `group:config:set`

## Mail templates management
* [ ] `mailtemplate:list`
* [ ] `mailtemplate:add`
* [ ] `mailtemplate:delete`
* [ ] `mailtemplate:get`
* [ ] `mailtemplate:set`

## Task management
* [ ] `task:list`
* [ ] `task:delete`
* [ ] `task:enable`
* [ ] `task:disable`

## System configuration
* [ ] `config:list`
* [ ] `config:get`
